[package]
name = "iv-core"
edition = "2024"

[dependencies]
rx-core = { path = "../../rx/rx-core" }

serde = { version = "*", features = ["derive"] }
serde_json = "*"

num = "*"
num-traits = "*"
geo = "*"
geo-types = "*"
