[package]
name = "iv-core"
version = "0.1.0"
authors = ["dayn9t <dayn9t@gmail.com>"]
edition = "2021"

[dependencies]
rx-core = { path = "../../rx/rx-core" }

serde = { version = "*", features = ["derive"] }
serde_json = "*"

num = "*"
num-traits = "*"
geo = "*"
geo-types = "*"
