[package]
name = "iv-va"
version = "0.1.0"
authors = ["dayn9t <dayn9t@gmail.com>"]
edition = "2024"

[dependencies]
iv-mm = { path = "../../iv-mm" }
iv-core = { path = "../../iv-core" }
rx-core = { path = "../../../rx/rx-core" }

opencv = "*"
