[package]
name = "iv-camera"
edition = "2024"

[dependencies]

iv-mm = { path = "../iv-mm" }
iv-core = { path = "../iv-core" }
rx-core = { path = "../../rx/rx-core" }

image = "*"

tracing = "*"
anyhow = "*"
thiserror = "*"

libcamera = "*"
