[package]
name = "iv-mm"
version = "0.1.0"
authors = ["dayn9t <dayn9t@gmail.com>"]
edition = "2018"

[dependencies]
rx = { path = "../../rx/rx" }
rx-db = { path = "../../rx/rx-db" }
rx-net = { path = "../../rx/rx-net" }

serde = { version = "*", features = ["derive"] }
serde_json = "*"